version: "3.8"

services:
  trend-app:
    image: ${IMAGE_NAME:-saidoc540/trend-app-dev}:${IMAGE_TAG:-latest}
    container_name: trend-app
    restart: always
    ports:
      - "80:80"
    # If you want to build locally instead of pull from Docker Hub, use:
    # build: .
